### ISSUE TITLE
UE Version 4.26 Support

### ISSUE THREAD

**Issue by cemcocu** [secretlocation/azure-kinect-unreal#18]
## Suggestion

Hello ,

Are there a plan to update UE version 4.26 support as soon?

Thanks.

**Comment by bigbigskies** [comment]
> ## Suggestion
> Hello ,
> 
> Are there a plan to update UE version 4.26 support as soon?
> 
> Thanks.

Same question here. Will there be support for UE 4.26 soon?

**Comment by Tokusei** [comment]
hi, you can rebuild the plugin and it works in UE4.26.1

**Comment by bigbigskies** [comment]
> hi, you can rebuild the plugin and it works in UE4.26.1

Tried rebuilding by generating visual studio file, but met with error:

Running C:/Program Files/Epic Games/UE_4.26/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="C:/Users/Yoyoyo/Desktop/Experimental/azure-kinect-unreal-1.5.1/azure-kinect-unreal-1.5.1/AzureKinect.uproject" -game -rocket -progress -log="C:\Users\Yoyoyo\Desktop\Experimental\azure-kinect-unreal-1.5.1\azure-kinect-unreal-1.5.1/Saved/Logs/UnrealVersionSelector-2021.02.20-07.13.14.log"
Discovering modules, targets and source code for project...
While compiling C:\Program Files\Epic Games\UE_4.26\Engine\Intermediate\Build\BuildRules\UE4Rules.dll:
error CS0042: Unexpected error creating debug information file 'c:\Program Files\Epic Games\UE_4.26\Engine\Intermediate\Build\BuildRules\UE4Rules.PDB' -- 'c:\Program Files\Epic Games\UE_4.26\Engine\Intermediate\Build\BuildRules\UE4Rules.pdb: Access is denied.
ERROR: Unable to compile source files.

**Comment by cgndev** [comment]
I did rebuild for UE 4.26.1 ..  It is succecfuly. but it is not works in 4.26.1 without error.. just led blink once at initialize. 
how do i solve?  sorry for bad English.

**Comment by cgndev** [comment]
> I did rebuild for UE 4.26.1 .. It is succecfuly. but it is not works in 4.26.1 without error.. just led blink once at initialize.
> how do i solve? sorry for bad English.

I solve it with delete 'Plugin/AzureKinectUnreal/Binaries' folder and rebuild.

**Comment by MrPantherM** [comment]
Just jumping back in this thread - are we able to use Kinect depth and RGB
sensors with Niagara now? Would love this
